### ISSUE TITLE
Extension of the OMTD-AgroPortal to SIFR BioPortal

### ISSUE THREAD

**Issue by jonquet** [agroportal/ncboproxy#2]
This is similar to #1 but for the SIFR BioPortal: 
http://services.bioportal.lirmm.fr/ontologies?format=omtd-share

**Comment by twktheainur** [comment]
@jonquet @antool Nothing to do in particular, current implementation will function the same on Agroportal, SIFR Bioportal and Stageportal. As soon as testing on stage is complete, we can deploy in production on Agroportal and SIFR Bioportal

**Comment by twktheainur** [comment]
Now in production, commit 5e8844d

**Comment by jonquet** [comment]
A few working examples:

All ontologies
http://services.bioportal.lirmm.fr/ontologies/?format=omtd-share

One ontology
http://services.bioportal.lirmm.fr/ontologies/MSHFRE/?format=omtd-share
